routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function(){
    Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

    // begin: admin ke route
    Route::get('/cpanel/dashboard', 'admin\DashboardController@index')->name('cpanel.dashboard');
    Route::get('/cpanel/dashboard/getlogs', 'admin\DashboardController@getLogs')->name('cpanel.datatable.logs');
    Route::get('/cpanel/dashboard/getteams', 'admin\DashboardController@getTeams')->name('cpanel.datatable.teams');
    Route::get('/cpanel/dashboard/{team}/getmembers', 'admin\DashboardController@getMembers')->name('cpanel.datatable.members');
    Route::get('/cpanel/member/{member}/dashboard', 'member\DashboardController@index')->name('cpanel.member.dashboard');

    Route::resource('/cpanel/users', 'admin\UsersController');
    Route::get('/cpanel/users/{user}/addToTeam', 'admin\UsersController@addToTeamView')->name('cpanel.users.addToTeamView');
    Route::put('/cpanel/users/{user}/addToTeam', 'admin\UsersController@addToTeam')->name('cpanel.users.addToTeam');
    Route::get('/cpanel/datatable/getusers', 'admin\UsersController@getUsers')->name('cpanel.datatable.users');

    Route::get('/cpanel/teams', 'admin\TeamsController@index')->name('cpanel.teams.index');
    Route::get('/cpanel/teams/{team}', 'admin\TeamsController@show')->name('cpanel.teams.show');
    Route::get('/cpanel/team/create', 'admin\TeamsController@create')->name('cpanel.teams.create');
    Route::post('/cpanel/teams', 'admin\TeamsController@store')->name('cpanel.teams.store');

    Route::get('/cpanel/team/{team}/projects/create', 'admin\ProjectsController@create')->name('cpanel.projects.create');
    Route::post('/cpanel/team/{team}/projects', 'admin\ProjectsController@store')->name('cpanel.projects.store');
    Route::get('/cpanel/team/{team}/projects', 'leader\ProjectsController@index')->name('cpanel.projects.index');
    Route::get('/cpanel/project/{project}', 'leader\ProjectsController@show')->name('cpanel.projects.show');

    Route::get('/cpanel/{user}/edit', 'admin\AdminsController@edit')->name('cpanel.edit');
    Route::put('/cpanel/{user}', 'admin\AdminsController@update')->name('cpanel.update');
    // end: admin ke route

    // begin: leaders ke route
    Route::get('/leader/dashboard', 'leader\DashboardController@index')->name('leader.dashboard');
    Route::get('/leader/dashboard/getlogs', 'leader\DashboardController@getLogs')->name('leader.datatable.logs');
    Route::get('/leader/dashboard/getmembers', 'leader\DashboardController@getMembers')->name('leader.datatable.members');
    Route::get('/leader/member/{member}/dashboard', 'member\DashboardController@index')->name('leader.member.dashboard');

    Route::get('/leader/projects', 'leader\ProjectsController@index')->name('leader.projects.index');
    Route::get('/leader/project/{project}', 'leader\ProjectsController@show')->name('leader.projects.show');
    Route::resource('/leader/project/{project}/tickets', 'leader\TicketsController');
    Route::get('/leader/project/{project}/ticket/{ticket}', 'leader\TicketsController@show')->name('leader.tickets.show');
    Route::post('/leader/project/{project}/ticket/{ticket}/query', 'leader\QueriesController@store')->name('leader.query.store');
    Route::get('/leader/project/{project}/ticket/{ticket}/status', 'leader\TicketsController@status')->name('leader.tickets.status');
    Route::put('/leader/project/{project}/ticket/{ticket}/status', 'leader\TicketsController@statusUpdate')->name('leader.tickets.status-update');
    Route::get('/leader/project/{project}/ticket/{ticket}/assign', 'leader\TicketsController@assign')->name('leader.tickets.assign');
    Route::put('/leader/project/{project}/ticket/{ticket}/assign-ticket', 'leader\TicketsController@assignTicket')->name('leader.tickets.assign-ticket');

    Route::post('/ajax', 'leader\AjaxController@getData')->name('leader.ajax.getdata');

    Route::get('/leader/{user}/edit', 'leader\LeadersController@edit')->name('leader.edit');
    Route::put('/leader/{user}', 'leader\LeadersController@update')->name('leader.update');
    // end: leaders ke route

    // begin: members ke route
    Route::get('/members/dashboard', 'member\DashboardController@index')->name('member.dashboard');
    Route::get('/members/dashboard/getlogs', 'member\DashboardController@getLogs')->name('member.datatable.logs');
    Route::post('/member/ajax', 'member\AjaxController@getData')->name('member.ajax.getdata');
    Route::get('/members/projects', 'member\ProjectsController@index')->name('member.projects.index');
    Route::get('/members/project/{project}', 'member\ProjectsController@show')->name('member.projects.show');
    Route::get('/members/project/{project}/ticket/{ticket}', 'member\TicketsController@show')->name('member.tickets.show');
    Route::post('/members/project/{project}/ticket/{ticket}/query', 'member\QueriesController@store')->name('member.query.store');
    Route::put('/member/project/{project}/ticket/{ticket}/resolve', 'member\TicketsController@resolve')->name('member.tickets.resolve');
    Route::put('/member/project/{project}/ticket/{ticket}/unresolve', 'member\TicketsController@unresolve')->name('member.tickets.unresolve');

    Route::get('/member/{member}/edit', 'member\MembersController@edit')->name('member.edit');
    Route::put('/member/{member}', 'member\MembersController@update')->name('member.update');
    // end: members ke route
});

app/Query.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Query extends Model
{
    protected $fillable = [
        'ticket_id',
        'member_id',
        'query'
    ];

    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }

    public function user() {
        return $this->belongsTo(User::class, 'member_id');
    }
}

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Ticket extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'project_id',
        'member_id',
        'title',
        'description',
        'labels',
        'due',
        'difficulty_level',
        'status',
        'assigned_at',
        'resolved_at',
        'attachments',
    ];

    protected $dates = [
        'due',
        'assigned_at',
        'resolved_at'
    ];

    public function getDueDateAttribute() {
        return $this->due->diffForHumans();
    }

    public function getAssignedDateAttribute() {
        return $this->assigned_at->diffForHumans();
    }

    public function getResolvedDateAttribute() {
        return $this->resolved_at->diffForHumans();
    }

    public function project() {
        return $this->belongsTo(Project::class);
    }

    public function member() {
        return $this->belongsTo(User::class, 'member_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Storage;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'team_id',
        'name',
        'email',
        'password',
        'role',
        'image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * HELPER METHODS
     */
    public function isAdmin(){
        return $this->role === 'admin';
    }

    public function isLeader(){
        return $this->role === 'leader';
    }

    public function isMember(){
        return $this->role === 'member';
    }

    public function isNaive(){
        return $this->role === 'naive';
    }

    public function deleteImage() {
        Storage::delete($this->image);
    }

    public function percentage($percentage) {
        if($percentage <= 30)
            return "<span class='text-danger font-weight-bold'>$percentage%</span>";
        else if ($percentage > 30 && $percentage < 75)
            return "<span class='text-warning font-weight-bold'>$percentage%</span>";

        return "<span class='text-success font-weight-bold'>$percentage%</span>";
    }

    /**
     * ACCESSORS
     */
    public function getAvatarAttribute(){
        $size = 36;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}&color=22b9ff&background=rgba(34,%20185,%20255,%200.1)";
    }

    /**
     * RELATIONSHIP FUNCIONS
     */
    public function team() {
        return $this->belongsTo(Team::class);
    }

    public function tickets() {
        return $this->hasMany(Ticket::class, 'member_id');
    }

    public function queries() {
        return $this->hasMany(Query::class, 'member_id');
    }

    public function performance() {
        return $this->hasOne(Performance::class, 'member_id');
    }

    public function logs() {
        return $this->hasMany(Log::class, 'member_id');
    }
}

app/Http/Controllers/leader/AjaxController.php
<?php

namespace App\Http\Controllers\leader;

use App\Http\Controllers\Controller;
use App\Performance;
use App\Ticket;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AjaxController extends Controller
{
    public function getData(Request $request){
        if($request->get('getMembers')) {
            $members = User::where('team_id', $request->teamID)->where('role', 'member')->get();
            return json_encode($members);

        } else if ($request->get('getBestOrAvailableMember')) {
            // finding the avaibale member
            $membersID = User::where('team_id', $request->teamID)->where('role', 'member')->pluck('id')->toArray();

            $membersEligibleForAssigningTask = DB::select(DB::raw("SELECT member_id, ((approved_tickets - unresolved_tickets) / total_tickets) as ticketCalculation FROM `performances` p1 WHERE currently_assigned_tickets in (SELECT MIN(`currently_assigned_tickets`) FROM `performances` WHERE `member_id` in (" . implode(', ', $membersID). ")) AND `member_id` in (" . implode(', ', $membersID). ") ORDER BY ticketCalculation DESC"));

            if(sizeof($membersEligibleForAssigningTask) > 1)
            {
                $free_members_id = array();
                $i = 0;
                foreach($membersEligibleForAssigningTask as $memberEligibleForAssigningTask) {
                    $free_members_id[$i++] = $memberEligibleForAssigningTask->member_id;
                }

                $bestMemberForAssigningTask = DB::select(DB::raw("SELECT member_id, sum((resolved_at - assigned_at)) as time_constraint FROM `tickets` WHERE `status` in ('resolved', 'approved') AND member_id in (" . implode(', ', $free_members_id). ") GROUP BY member_id ORDER BY time_constraint LIMIT 1"));

                if(sizeof($bestMemberForAssigningTask))
                    $eligibleMember = User::where('id', $bestMemberForAssigningTask[0]->member_id)->first();
                else
                    $eligibleMember = User::where('id', $free_members_id[0])->first();
            } else {
                $eligibleMember = User::where('id', $membersEligibleForAssigningTask[0]->member_id)->first();
            }

            return json_encode($eligibleMember);
        } else if($request->get('getTickets')){
            $team_id = User::where('id', $request->userID)->pluck('team_id')->first();
            $member_id = User::where('team_id', $team_id)->where('role', 'member')->pluck('id')->toArray();
            $tickets = Ticket::whereIn('member_id', $member_id)->where('status', $request->status)->with(['project', 'member'])->get();
            return json_encode($tickets);
        }
    }
}

app/Http/Controllers/leader/DashboardController.php
<?php

namespace App\Http\Controllers\leader;

use App\Http\Controllers\Controller;
use App\Log;
use App\Project;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
    public function index() {
        $user = User::where('id', auth()->user()->id)->first();
        $members = User::where('team_id', auth()->user()->team_id)->where('role', 'member')->get();
        $projects = Project::where('team_id', auth()->user()->team_id)->get();

        $membersID = $members->pluck('id')->toArray();

        if($membersID) {
            $performance = DB::select(DB::raw("SELECT sum(((approved_tickets - unresolved_tickets) / total_tickets) * 100) / " . sizeof($membersID) . " as ticketCalculation FROM `performances` p1 WHERE `member_id` in (" . implode(', ', $membersID). ") ORDER BY ticketCalculation DESC"));
        } else {
            $performance = array();
        }

        auth()->user()->unreadNotifications->markAsRead();
        $notifications = auth()->user()->notifications()->paginate(10);
        return view('leader.dashboard', compact([
            'user',
            'members',
            'membersID',
            'projects',
            'performance',
            'notifications'
        ]));
    }

    public function getLogs() {
        return \DataTables::of(Log::where('member_id', auth()->user()->id)->get())
            ->addIndexColumn()
            ->make(true);
    }

    public function getMembers() {
        $users = User::where('team_id', auth()->user()->team_id)->where('role', 'member')->get();
        if($users) {
            return \DataTables::of($users)
                ->addIndexColumn()
                ->addColumn('image', function (User $user) {
                    if ($user->image)
                        return '<img src=' . asset("storage/" . $user->image) . ' alt="Student Image" width="128">';
                    else
                        return '<img src=' . asset("storage/users/neutral.png") . ' alt="Student Image" width="128">';
                })
                ->addColumn('performance', function (User $user) {
                    $performance = DB::select(DB::raw("SELECT member_id, ((approved_tickets - unresolved_tickets) / total_tickets) * 100 as ticketCalculation FROM `performances` p1 WHERE currently_assigned_tickets in (SELECT MIN(`currently_assigned_tickets`) FROM `performances` WHERE `member_id` = $user->id) AND `member_id` = $user->id ORDER BY ticketCalculation DESC"));
                    return sizeof($performance) ? $user->percentage(round($performance[0]->ticketCalculation, 2)) : $user->percentage(0);
                })
                ->addColumn('actions', function (User $user) {
                    $actionButtons = "<div class='d-flex'>";

                    if (auth()->user()->can('view', User::class)) {
                        $actionButtons .= "<a href='" . route('leader.member.dashboard', $user->id) . "' class='btn btn-icon btn-outline-success mr-1'><i class='fa fa-eye'></i></a>";
                    }
                    return $actionButtons . '</div>';
                })
                ->rawColumns(['image', 'performance', 'actions'])
                ->make(true);
        }
    }
}

app/Http/Controllers/leader/LeadersController.php
<?php

namespace App\Http\Controllers\leader;

use App\Http\Controllers\Controller;
use App\Http\Requests\Members\UpdateMemberRequest;
use App\Http\Requests\Users\UpdateUserRequest;
use App\Project;
use App\User;
use Illuminate\Http\Request;

class LeadersController extends Controller
{
    public function edit(User $user) {
        $this->authorize('update', User::class);

        auth()->user()->unreadNotifications->markAsRead();
        $notifications = auth()->user()->notifications()->paginate(10);

        return view('leader.edit', compact([
            'user',
            'notifications'
        ]));
    }

    public function update(UpdateUserRequest $request, User $user) {
        $this->authorize('update', User::class);

        $data = $request->only(['name', 'email']);

        if ($request->hasFile('image')) {
            $image = $request->image->store('users');
            $user->deleteImage();
            $data['image'] = $image;
        }

        $user->update($data);

        session()->flash('success', "Personal Details Updated Successfully");
        return redirect(route('leader.dashboard'));
    }
}

resources/views/leader/tickets/assign.blade.php
@extends('layouts.template')

@section('title', 'Leader | Assign Ticket')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card shadow mb-4">
            <!-- CARD HEADER -->
            <div class="card-header">
                <h6 class="m-0 font-weight-bold text-primary">
                    <i class="fa fa-plus"></i> Assign Ticket
                </h6>
            </div>
            <!-- END OF CARD HEADER -->

            <!-- CARD BODY -->
            <div class="card-body">
                <form class="kt-form" action="{{ route('leader.tickets.assign-ticket', [$project->id, $ticket->id])}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label for="member_id">Member</label>
                            <select name="member_id" id="member_id" class="form-control select2">
                                <option value="" selected disabled>Select Member</option>
                                @foreach ($members as $member)
                                    <option value="{{ $member->id }}" {{ old('member_id') == $member->id ? 'selected' : '' }}>{{ $member->name }}</option>
                                @endforeach
                            </select>
                            @error('member_id')
                                <p class="text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="form-group col-md-12">
                            <label class="kt-checkbox kt-checkbox--bold kt-checkbox--brand">
                                <input type="checkbox" id="automatic_assignment" onchange="automaticAssignment({{ auth()->user()->team_id }})"> Automatic Assignment
                                <span></span>
                            </label>
                        </div>

                        <div class="form-group col-md-12 text-muted" id="assigned_to"></div>
                    </div>
                    <button type="submit" class="btn btn-outline-primary btn-sm m-1"><i class='fa fa-pen'></i> Assign</button>
                </form>
            </div>
            <!-- END OF CARD BODY -->
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script>
        $('#member_id').select2();

        function automaticAssignment(teamID) {
            if($("#automatic_assignment").is(':checked')) {
                $("#member_id").attr('disabled', true);

                route = "{{ route('leader.ajax.getdata') }}";
                $.ajax({
                    url: route,
                    method: "POST",
                    data:{
                        _token: "{{ csrf_token() }}",
                        getBestOrAvailableMember: true,
                        teamID: teamID
                    },
                    dataType: 'json',
                    success: function(member){
                        console.log(member);

                        eligibleMember = `
                            <input type="hidden" name="member_id" value=${member.id}>
                            <span>Assigning To : ${member.name}</span>
                        `;

                        $("#assigned_to").append(eligibleMember);
                    }
                });
            } else {
                $("#assigned_to").empty();
                $("#member_id").attr('disabled', false);
            }
        }
    </script>
@endsection

resources/views/leader/tickets/show.blade.php
@extends('layouts.template')

@section('title', 'Ticket | ' . $ticket->title)

@section('content')
    @include('layouts.partials._message')
    <div class="row mt-4 pl-2">
        <div class="col-md-12 mb-4">
            <div class="card shadow h-100 py-2" style="border-left: dashed 2px #CCC">
                <div class="card-body">
                    <div class="row p-3">
                        <div class="col mr-2">
                            <div class="text-lg font-weight-bold text-gray-800 text-uppercase mb-1">
                                <span>{{ $ticket->title }}</span>
                            </div>
                        </div>
                        <div class="col-md-12 mr-2">
                            <div class="pb-3">
                                @php
                                    $labels = explode(",", $ticket->labels);
                                    $colors = ["success", "info", "warning", "danger", "primary"];
                                @endphp
                                @foreach ($labels as $label)
                                    <span class="btn btn-sm btn-outline-{{ Arr::random($colors) }}">{{ $label }}</span>
                                @endforeach
                            </div>

                            <div class="pb-3 text-gray-600">
                                {{ $ticket->description }}
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="d-flex justify-content-between pb-3">
                                <div>
                                    <span class="btn btn-outline-danger btn-bold btn-sm btn-upper">
                                        <i class="fa fa-clock"></i> {{ $ticket->due_date }}
                                    </span>
                                    <span class="btn btn-outline-warning btn-bold btn-sm btn-upper">
                                        <i class="fas fa-file-signature"></i> {{ $ticket->assigned_date }}
                                    </span>
                                    @if ($ticket->status == "resolved" || $ticket->status == "approved")
                                        <span class="btn btn-outline-success btn-bold btn-sm btn-upper">
                                            <i class="fas fa-clipboard-list"></i> {{ $ticket->resolved_date }}
                                        </span>
                                    @endif
                                </div>

                                <div>
                                    <img src="{{ $ticket->member->avatar }}" alt="">
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <h3>Queries</h3>

        <div class="row mr-2 mb-5">
            @foreach ($queries as $query)
                @if ($query->user->role == "leader")
                    <div class="col-md-12" style="padding-left: 45%">
                        <div class="card shadow h-100 py-2" style="border-right: dashed 2px #AAA">
                @else
                    <div class="col-md-12" style="padding-right: 45%">
                        <div class="card shadow h-100 py-2" style="border-left: dashed 2px #AAA">
                @endif
                            <div class="card-body pb-1">
                                <div class="row p-3">
                                    <div class="col-md-12 mr-2">
                                        <div class="text-lg text-gray-800 mb-1">
                                            <span>{{ $query->query }}</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="d-flex justify-content-end">
                                    <div class="kt-widget19__text pb-2">
                                        <i class="flaticon2-time"> </i> {{ $query->created_date }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            @endforeach
        </div>

        @if ($ticket->status == "assigned" || $ticket->status == "resolved")
            <div class="card-body" style="border-top: solid 1px #EEE">
                <form action="{{ route('member.query.store', [$project->id, $ticket->id]) }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <textarea name="comment" id="comment" cols="10" rows="3" class="w-100"></textarea>
                        @error('comment')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group d-flex justify-content-end">
                        <button type="submit" class="btn btn-outline-success">Submit</button>
                    </div>
                </form>
            </div>
        @endif
    </div>
@endsection

@section('styles')
    <style>
        #comment {
            padding: 10px;
            font-size: 1.1rem;
            border-radius: 5px;
            border-color: #CCC;
            resize: none;
        }

        #comment:active,
        #comment:focus {
            border: solid 1px #AAA!important;
            outline: 0;
        }
    </style>
@endsection