routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function(){
    Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

    // begin: admin ke route
    Route::get('/cpanel/dashboard', 'admin\DashboardController@index')->name('cpanel.dashboard');
    Route::get('/cpanel/dashboard/getlogs', 'admin\DashboardController@getLogs')->name('cpanel.datatable.logs');
    Route::get('/cpanel/dashboard/getteams', 'admin\DashboardController@getTeams')->name('cpanel.datatable.teams');
    Route::get('/cpanel/dashboard/{team}/getmembers', 'admin\DashboardController@getMembers')->name('cpanel.datatable.members');
    Route::get('/cpanel/member/{member}/dashboard', 'member\DashboardController@index')->name('cpanel.member.dashboard');

    Route::resource('/cpanel/users', 'admin\UsersController');
    Route::get('/cpanel/users/{user}/addToTeam', 'admin\UsersController@addToTeamView')->name('cpanel.users.addToTeamView');
    Route::put('/cpanel/users/{user}/addToTeam', 'admin\UsersController@addToTeam')->name('cpanel.users.addToTeam');
    Route::get('/cpanel/datatable/getusers', 'admin\UsersController@getUsers')->name('cpanel.datatable.users');

    Route::get('/cpanel/teams', 'admin\TeamsController@index')->name('cpanel.teams.index');
    Route::get('/cpanel/teams/{team}', 'admin\TeamsController@show')->name('cpanel.teams.show');
    Route::get('/cpanel/team/create', 'admin\TeamsController@create')->name('cpanel.teams.create');
    Route::post('/cpanel/teams', 'admin\TeamsController@store')->name('cpanel.teams.store');

    Route::get('/cpanel/team/{team}/projects/create', 'admin\ProjectsController@create')->name('cpanel.projects.create');
    Route::post('/cpanel/team/{team}/projects', 'admin\ProjectsController@store')->name('cpanel.projects.store');
    Route::get('/cpanel/team/{team}/projects', 'leader\ProjectsController@index')->name('cpanel.projects.index');
    Route::get('/cpanel/project/{project}', 'leader\ProjectsController@show')->name('cpanel.projects.show');

    Route::get('/cpanel/{user}/edit', 'admin\AdminsController@edit')->name('cpanel.edit');
    Route::put('/cpanel/{user}', 'admin\AdminsController@update')->name('cpanel.update');
    // end: admin ke route

    // begin: leaders ke route
    Route::get('/leader/dashboard', 'leader\DashboardController@index')->name('leader.dashboard');
    Route::get('/leader/dashboard/getlogs', 'leader\DashboardController@getLogs')->name('leader.datatable.logs');
    Route::get('/leader/dashboard/getmembers', 'leader\DashboardController@getMembers')->name('leader.datatable.members');
    Route::get('/leader/member/{member}/dashboard', 'member\DashboardController@index')->name('leader.member.dashboard');

    Route::get('/leader/projects', 'leader\ProjectsController@index')->name('leader.projects.index');
    Route::get('/leader/project/{project}', 'leader\ProjectsController@show')->name('leader.projects.show');
    Route::resource('/leader/project/{project}/tickets', 'leader\TicketsController');
    Route::get('/leader/project/{project}/ticket/{ticket}', 'leader\TicketsController@show')->name('leader.tickets.show');
    Route::post('/leader/project/{project}/ticket/{ticket}/query', 'leader\QueriesController@store')->name('leader.query.store');
    Route::get('/leader/project/{project}/ticket/{ticket}/status', 'leader\TicketsController@status')->name('leader.tickets.status');
    Route::put('/leader/project/{project}/ticket/{ticket}/status', 'leader\TicketsController@statusUpdate')->name('leader.tickets.status-update');
    Route::get('/leader/project/{project}/ticket/{ticket}/assign', 'leader\TicketsController@assign')->name('leader.tickets.assign');
    Route::put('/leader/project/{project}/ticket/{ticket}/assign-ticket', 'leader\TicketsController@assignTicket')->name('leader.tickets.assign-ticket');

    Route::post('/ajax', 'leader\AjaxController@getData')->name('leader.ajax.getdata');

    Route::get('/leader/{user}/edit', 'leader\LeadersController@edit')->name('leader.edit');
    Route::put('/leader/{user}', 'leader\LeadersController@update')->name('leader.update');
    // end: leaders ke route

    // begin: members ke route
    Route::get('/members/dashboard', 'member\DashboardController@index')->name('member.dashboard');
    Route::get('/members/dashboard/getlogs', 'member\DashboardController@getLogs')->name('member.datatable.logs');
    Route::post('/member/ajax', 'member\AjaxController@getData')->name('member.ajax.getdata');
    Route::get('/members/projects', 'member\ProjectsController@index')->name('member.projects.index');
    Route::get('/members/project/{project}', 'member\ProjectsController@show')->name('member.projects.show');
    Route::get('/members/project/{project}/ticket/{ticket}', 'member\TicketsController@show')->name('member.tickets.show');
    Route::post('/members/project/{project}/ticket/{ticket}/query', 'member\QueriesController@store')->name('member.query.store');
    Route::put('/member/project/{project}/ticket/{ticket}/resolve', 'member\TicketsController@resolve')->name('member.tickets.resolve');
    Route::put('/member/project/{project}/ticket/{ticket}/unresolve', 'member\TicketsController@unresolve')->name('member.tickets.unresolve');

    Route::get('/member/{member}/edit', 'member\MembersController@edit')->name('member.edit');
    Route::put('/member/{member}', 'member\MembersController@update')->name('member.update');
    // end: members ke route
});

resources/views/layouts/partials/_footer.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
      <div class="copyright text-center my-auto">
        <span>Copyright &copy; Your Ticket Management - 2020</span>
      </div>
    </div>
</footer>

resources/views/layouts/partials/_message.blade.php
@if(session()->has('success'))
    <div class="alert alert-success fade show" role="alert">
        <div class="alert-icon"><i class="flaticon2-check-mark"></i></div>
        <div class="alert-text">{{ session()->get('success') }}</div>
        <div class="alert-close">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"><i class="la la-close"></i></span>
            </button>
        </div>
    </div>
@endif

@if(session()->has('error'))
<div class="alert alert-warning fade show" role="alert">
    <div class="alert-icon"><i class="flaticon2-exclamation"></i></div>
    <div class="alert-text">{{ session()->get('error') }}</div>
    <div class="alert-close">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"><i class="la la-close"></i></span>
        </button>
    </div>
</div>
@endif

resources/views/layouts/partials/_sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center"
        href="
            @if(auth()->user()->isAdmin())
                {{ route('cpanel.dashboard') }}
            @elseif(auth()->user()->isLeader())
                {{ route('leader.dashboard') }}
            @else
                {{ route('member.dashboard') }}
            @endif
        ">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Ticket Management</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    @if (auth()->user()->isAdmin())
        <li class="nav-item">
        <a class="nav-link" href="{{ route('cpanel.dashboard') }}">
            <i class="fa fa-home"></i>
            <span>Dashboard</span></a>
        </li>
    @endif

    @if (auth()->user()->isLeader())
        <li class="nav-item">
        <a class="nav-link" href="{{ route('leader.dashboard') }}">
            <i class="fa fa-home"></i>
            <span>Dashboard</span></a>
        </li>
    @endif

    @if (auth()->user()->isMember() || auth()->user()->isNaive())
        <li class="nav-item">
        <a class="nav-link" href="{{ route('member.dashboard') }}">
            <i class="fa fa-home"></i>
            <span>Dashboard</span></a>
        </li>
    @endif

    <!-- Divider -->
    <hr class="sidebar-divider">

    @if (auth()->user()->isAdmin())
        <li class="nav-item">
        <a class="nav-link" href="{{ route('cpanel.teams.index') }}">
            <i class="fa fa-users"></i>
            <span>Teams</span></a>
        </li>
    @endif

    @if (auth()->user()->isAdmin())
        <li class="nav-item">
        <a class="nav-link" href="{{ route('users.index') }}">
            <i class="fa fa-user"></i>
            <span>Users</span></a>
        </li>
    @endif

    @if (auth()->user()->isLeader())
        <li class="nav-item">
        <a class="nav-link" href="{{ route('leader.projects.index') }}">
            <i class="fas fa-chart-line"></i>
            <span>Projects</span></a>
        </li>
    @endif

    @if (auth()->user()->isMember() && auth()->user()->tickets->count())
        <li class="nav-item">
        <a class="nav-link" href="{{ route('member.projects.index') }}">
            <i class="fas fa-chart-line"></i>
            <span>Projects</span></a>
        </li>
    @endif

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

  </ul>