routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function(){
    Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

    // begin: admin ke route
    Route::get('/cpanel/dashboard', 'admin\DashboardController@index')->name('cpanel.dashboard');
    Route::get('/cpanel/dashboard/getlogs', 'admin\DashboardController@getLogs')->name('cpanel.datatable.logs');
    Route::get('/cpanel/dashboard/getteams', 'admin\DashboardController@getTeams')->name('cpanel.datatable.teams');
    Route::get('/cpanel/dashboard/{team}/getmembers', 'admin\DashboardController@getMembers')->name('cpanel.datatable.members');
    Route::get('/cpanel/member/{member}/dashboard', 'member\DashboardController@index')->name('cpanel.member.dashboard');

    Route::resource('/cpanel/users', 'admin\UsersController');
    Route::get('/cpanel/users/{user}/addToTeam', 'admin\UsersController@addToTeamView')->name('cpanel.users.addToTeamView');
    Route::put('/cpanel/users/{user}/addToTeam', 'admin\UsersController@addToTeam')->name('cpanel.users.addToTeam');
    Route::get('/cpanel/datatable/getusers', 'admin\UsersController@getUsers')->name('cpanel.datatable.users');

    Route::get('/cpanel/teams', 'admin\TeamsController@index')->name('cpanel.teams.index');
    Route::get('/cpanel/teams/{team}', 'admin\TeamsController@show')->name('cpanel.teams.show');
    Route::get('/cpanel/team/create', 'admin\TeamsController@create')->name('cpanel.teams.create');
    Route::post('/cpanel/teams', 'admin\TeamsController@store')->name('cpanel.teams.store');

    Route::get('/cpanel/team/{team}/projects/create', 'admin\ProjectsController@create')->name('cpanel.projects.create');
    Route::post('/cpanel/team/{team}/projects', 'admin\ProjectsController@store')->name('cpanel.projects.store');
    Route::get('/cpanel/team/{team}/projects', 'leader\ProjectsController@index')->name('cpanel.projects.index');
    Route::get('/cpanel/project/{project}', 'leader\ProjectsController@show')->name('cpanel.projects.show');

    Route::get('/cpanel/{user}/edit', 'admin\AdminsController@edit')->name('cpanel.edit');
    Route::put('/cpanel/{user}', 'admin\AdminsController@update')->name('cpanel.update');
    // end: admin ke route

    // begin: leaders ke route
    Route::get('/leader/dashboard', 'leader\DashboardController@index')->name('leader.dashboard');
    Route::get('/leader/dashboard/getlogs', 'leader\DashboardController@getLogs')->name('leader.datatable.logs');
    Route::get('/leader/dashboard/getmembers', 'leader\DashboardController@getMembers')->name('leader.datatable.members');
    Route::get('/leader/member/{member}/dashboard', 'member\DashboardController@index')->name('leader.member.dashboard');

    Route::get('/leader/projects', 'leader\ProjectsController@index')->name('leader.projects.index');
    Route::get('/leader/project/{project}', 'leader\ProjectsController@show')->name('leader.projects.show');
    Route::resource('/leader/project/{project}/tickets', 'leader\TicketsController');
    Route::get('/leader/project/{project}/ticket/{ticket}', 'leader\TicketsController@show')->name('leader.tickets.show');
    Route::post('/leader/project/{project}/ticket/{ticket}/query', 'leader\QueriesController@store')->name('leader.query.store');
    Route::get('/leader/project/{project}/ticket/{ticket}/status', 'leader\TicketsController@status')->name('leader.tickets.status');
    Route::put('/leader/project/{project}/ticket/{ticket}/status', 'leader\TicketsController@statusUpdate')->name('leader.tickets.status-update');
    Route::get('/leader/project/{project}/ticket/{ticket}/assign', 'leader\TicketsController@assign')->name('leader.tickets.assign');
    Route::put('/leader/project/{project}/ticket/{ticket}/assign-ticket', 'leader\TicketsController@assignTicket')->name('leader.tickets.assign-ticket');

    Route::post('/ajax', 'leader\AjaxController@getData')->name('leader.ajax.getdata');

    Route::get('/leader/{user}/edit', 'leader\LeadersController@edit')->name('leader.edit');
    Route::put('/leader/{user}', 'leader\LeadersController@update')->name('leader.update');
    // end: leaders ke route

    // begin: members ke route
    Route::get('/members/dashboard', 'member\DashboardController@index')->name('member.dashboard');
    Route::get('/members/dashboard/getlogs', 'member\DashboardController@getLogs')->name('member.datatable.logs');
    Route::post('/member/ajax', 'member\AjaxController@getData')->name('member.ajax.getdata');
    Route::get('/members/projects', 'member\ProjectsController@index')->name('member.projects.index');
    Route::get('/members/project/{project}', 'member\ProjectsController@show')->name('member.projects.show');
    Route::get('/members/project/{project}/ticket/{ticket}', 'member\TicketsController@show')->name('member.tickets.show');
    Route::post('/members/project/{project}/ticket/{ticket}/query', 'member\QueriesController@store')->name('member.query.store');
    Route::put('/member/project/{project}/ticket/{ticket}/resolve', 'member\TicketsController@resolve')->name('member.tickets.resolve');
    Route::put('/member/project/{project}/ticket/{ticket}/unresolve', 'member\TicketsController@unresolve')->name('member.tickets.unresolve');

    Route::get('/member/{member}/edit', 'member\MembersController@edit')->name('member.edit');
    Route::put('/member/{member}', 'member\MembersController@update')->name('member.update');
    // end: members ke route
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Storage;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'team_id',
        'name',
        'email',
        'password',
        'role',
        'image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * HELPER METHODS
     */
    public function isAdmin(){
        return $this->role === 'admin';
    }

    public function isLeader(){
        return $this->role === 'leader';
    }

    public function isMember(){
        return $this->role === 'member';
    }

    public function isNaive(){
        return $this->role === 'naive';
    }

    public function deleteImage() {
        Storage::delete($this->image);
    }

    public function percentage($percentage) {
        if($percentage <= 30)
            return "<span class='text-danger font-weight-bold'>$percentage%</span>";
        else if ($percentage > 30 && $percentage < 75)
            return "<span class='text-warning font-weight-bold'>$percentage%</span>";

        return "<span class='text-success font-weight-bold'>$percentage%</span>";
    }

    /**
     * ACCESSORS
     */
    public function getAvatarAttribute(){
        $size = 36;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}&color=22b9ff&background=rgba(34,%20185,%20255,%200.1)";
    }

    /**
     * RELATIONSHIP FUNCIONS
     */
    public function team() {
        return $this->belongsTo(Team::class);
    }

    public function tickets() {
        return $this->hasMany(Ticket::class, 'member_id');
    }

    public function queries() {
        return $this->hasMany(Query::class, 'member_id');
    }

    public function performance() {
        return $this->hasOne(Performance::class, 'member_id');
    }

    public function logs() {
        return $this->hasMany(Log::class, 'member_id');
    }
}

app/Http/Controllers/admin/UsersController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Users\CreateUserRequest;
use App\Notifications\UserAddedToTeamNotification;
use App\Notifications\UserCreationNotification;
use Illuminate\Support\Str;
use App\Team;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UsersController extends Controller
{
    public function index()
    {
        $this->authorize('view', User::class);
        return view('admin.users.index');
    }

    public function getUsers(){
        $users = User::where('role', 'naive')->get();
        return \DataTables::of($users)
                ->addIndexColumn()
                ->addColumn('actions', function(User $user){
                    $actionButtons = "";
                    if(auth()->user()->can('update', $user)){
                        $actionButtons .= "
                                <a class='btn btn-outline-info btn-sm m-1' href='" . route('cpanel.users.addToTeamView', $user->id) . "'><i class='fa fa-users'></i>
                                    Add to Team
                                </a>";
                    }
                    return $actionButtons;
                })
                ->rawColumns(['actions'])
                ->make(true);
    }

    public function create()
    {
        $this->authorize('create', User::class);
        $teams = Team::with(['users' => function($query){
            $query->where('role', 'leader');
        }])->get();

        return view('admin.users.create', compact([
            'teams'
        ]));
    }

    public function store(CreateUserRequest $request)
    {
        $this->authorize('create', User::class);

        $team = Team::where('id', $request->team_id)->get();
        if($request->role === "leader") {
            $user = User::where('team_id', $request->team_id)->where('role', 'leader');
            if($user !== null) {
                session()->flash('error', $request->name . ' cannot be assigned as team leader of ' . $team[0]->name . ' as it already has a leader!');
                return redirect(route('users.index'));
            }
        }

        $image = '';
        if ($request->hasFile('image')) {
            $image = $request->image->store('users');
        }

        if($request->role)
            $role = $request->role;
        else
            $role = 'naive';

        $password = Str::random(8);
        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'role' => $role,
            'image' => $image,
            'team_id' => $request->team_id,
            'password' => Hash::make($password)
        ]);

        $user->notify(new UserCreationNotification($user, $password));

        session()->flash('success', "User Created Successfully");
        return redirect(route('users.index'));
    }

    public function addToTeamView(User $user) {
        $this->authorize('addToTeam', $user);
        $teams = Team::with(['users' => function($query){
            $query->where('role', 'leader');
        }])->get();

        return view('admin.users.addToTeamView', compact([
            'user',
            'teams'
        ]));
    }

    public function addToTeam(Request $request, User $user) {
        $this->authorize('addToTeam', User::class);

        $team = Team::where('id', $request->team_id)->first();
        if($request->role == "leader") {
            $leader = User::where('team_id', $request->team_id)->where('role', 'leader')->first();
            if($leader) {
                session()->flash('error', $request->name . ' cannot be assigned as team leader of "' . $team->name . '" as it already has a leader!');
                return redirect(route('users.index'));
            }
        }

        $user->update([
            'role'=>$request->role,
            'team_id'=>$request->team_id
        ]);

        $user->notify(new UserAddedToTeamNotification($user));

        session()->flash('success', $user->name . ' is now a "' . $request->role . '" of team "' . $team->name . '" !');
        return redirect(route('users.index'));
    }
}

resources/views/admin/users/addToTeamView.blade.php
@extends('layouts.template')

@section('title', 'Admin | Add To Team')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <!-- CARD HEADER -->
                <div class="card-header">
                    <h6 class="m-0 font-weight-bold text-primary">
                        <i class="fa fa-plus"></i> Add To Team
                    </h6>
                </div>
                <!-- END OF CARD HEADER -->

                <!-- CARD BODY -->
                <div class="card-body">
                    <form class="kt-form" action="{{ route('cpanel.users.addToTeam', $user->id)}}" method="POST">
                        @csrf
                        @method("PUT")
                        <div class="row">
                            <div class="form-group col-md-12">
                                <label for="name">Name</label>
                                <input type="text" value="{{ old('name', $user->name) }}" class="form-control @error('name') is-invalid @enderror" name="name" id="name" readonly>
                                @error('name')
                                <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>

                            <div class="form-group col-md-12">
                                <label for="team_id">Team</label>
                                <div>
                                    <select class="form-control select2" id="team_id" name="team_id">
                                        <option selected disabled>Select Team</option>
                                        @foreach($teams as $team)
                                            <option value="{{$team->id}}" {{ ($team->id == old('team_id')) ? 'selected' : '' }}>{{$team->name}} - {{ sizeof($team->users) ? $team->users[0]->name : 'No Leader Assigned Yet'}}</option>
                                        @endforeach
                                    </select>
                                    @error('team_id')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group col-md-12">
                                <label for="role">Role</label>
                                <div>
                                    <select class="form-control select2" id="role" name="role">
                                        <option selected disabled>Select Role</option>
                                        <option value="member">Member</option>
                                        <option value="leader">Leader</option>
                                    </select>
                                    @error('role')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-outline-primary btn-sm m-1"><i class='fa fa-plus'></i> Add</button>
                    </form>
                </div>
                <!-- END OF CARD BODY -->
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $('.select2').select2();
    </script>
@endsection

resources/views/admin/users/create.blade.php
@extends('layouts.template')

@section('title', 'Admin | Create User')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card shadow mb-4">
            <!-- CARD HEADER -->
            <div class="card-header">
                <h6 class="m-0 font-weight-bold text-primary">
                    <i class="fa fa-plus"></i> Add User
                </h6>
            </div>
            <!-- END OF CARD HEADER -->

            <!-- CARD BODY -->
            <div class="card-body">
                <form class="kt-form" action="{{ route('users.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label>Name</label>
                            <input type="text" placeholder="Enter name" value="{{old('name')}}"
                                   class="form-control @error('name') is-invalid @enderror"
                                   name="name" id="name">
                            @error('name')
                                <p class="text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="form-group col-md-12">
                            <label>Email</label>
                            <input type="email" placeholder="Enter email" value="{{old('email')}}"
                                   class="form-control @error('email') is-invalid @enderror"
                                   name="email" id="email">
                            @error('email')
                                <p class="text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="form-group col-md-12">
                            <label for="image">Image</label>
                            <input type="file" class="form-control @error('image') is-invalid @enderror" name="image" id="image">
                            @error('image')
                                <p class="text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="form-group col-md-12">
                            <label for="team_id">Team</label>
                            <div>
                                <select class="form-control select2" id="team_id" name="team_id">
                                    <option selected disabled>Select Team</option>
                                    @foreach($teams as $team)
                                    <option value="{{$team->id}}" {{ ($team->id == old('team_id')) ? 'selected' : '' }}>{{$team->name}} - {{ $team->users[0]->name }}</option>
                                    @endforeach
                                </select>
                                @error('team_id')
                                <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group col-md-12">
                            <label for="role">Role</label>
                            <div>
                                <select class="form-control select2" id="role" name="role">
                                    <option selected disabled>Select Role</option>
                                    <option value="member" {{ ( old('role')) == "member" ? 'selected' : '' }}>Member</option>
                                    <option value="leader" {{ ( old('role')) == "leader" ? 'selected' : '' }}>Leader</option>
                                </select>
                                @error('role')
                                <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-outline-primary btn-sm m-1"><i class='fa fa-plus'></i> Add</button>
                </form>
            </div>
            <!-- END OF CARD BODY -->
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script>
        $('.select2').select2();
    </script>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.template')

@section('title', 'Admin | Manage Users')

@section('content')
    @include('layouts.partials._message')

    <div class="row">
        <div class="col-md-12 d-flex justify-content-end mb-3" id="create_user_button">
            <a href="{{ route('users.create') }}" class="btn btn-outline-primary">
                <i class="fa fa-plus"></i>
                Create User
            </a>
        </div>
    </div>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Manage Users</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="users_table" width="100%" cellspacing="0">
                    <div id="export-buttons"></div>
                    <thead>
                        <tr>
                            <th>Sr No.</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>

    <form action="#" method='POST' id='makeAdminForm'>
        @csrf
        @method('PUT')
    </form>
@endsection


@section('styles')
    <style>
        #create_user_button {
            padding-right: 1.8rem!important;
        }

        #export-buttons .dt-buttons.btn-group.flex-wrap {
            position: absolute;
            left: 84.4%;
            top: .4rem;
        }

        #export-buttons .btn.buttons-html5 {
            background-color: #FFF;
            border-color: #CCC;
            color: #333;
        }
    </style>
@endsection

@section('scripts')
<script>
    $(document).ready(function() {
        var TableDatatables = function(){
            var handleUsersTable = function(){
                var oTable = $('#users_table').DataTable({
                    processing: true,
                    serverSide: true,
                    responsive: true,
                    ajax: "{{ route('cpanel.datatable.users') }}",
                    columns: [
                        {data: 'DT_RowIndex', orderable: false, searchable: false },
                        {data: 'name', name: 'name'},
                        {data: 'email', name: 'email'},
                        {data: 'role', name:'role'},
                        {data: 'actions', name:'actions', orderable: false, searchable: false}
                    ]
                });
                new $.fn.dataTable.Buttons(oTable, {
                    buttons:[
                        'copy', 'csv', 'pdf'
                    ]
                } );
                oTable.buttons().container()
                    .appendTo( $('#export-buttons') );
            }
            return {
                //main function to handle all the datatables
                init: function () {
                    handleUsersTable();
                }
            }
        }();
        jQuery(document).ready(function () {
            TableDatatables.init();
        });
    });
</script>
@endsection